function createStemfigure(XMatrix1, YMatrix1, DMatrix1)
%CREATEFIGURE1(XMatrix1, YMatrix1, DMatrix1)
%  XMATRIX1:  errorbar x matrix data
%  YMATRIX1:  errorbar y matrix data
%  DMATRIX1:  errorbar delta matrix data

%  Auto-generated by MATLAB on 26-Jan-2018 20:09:55

% Create figure
figure1 = figure('Name','Figure');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple error bars using matrix input to errorbar
errorbar1 = errorbar(XMatrix1,YMatrix1,DMatrix1,'.',...
    'MarkerSize',20,...
    'CapSize',15,...
    'Color',[0 0 0]);
set(errorbar1(1),'DisplayName','Public attribute');
set(errorbar1(2),'DisplayName','Private attribute');

% Stem
linewidth = 1.5;
stem(XMatrix1(:,1),YMatrix1(:,1),'k','Linewidth',linewidth)
hold on
stem(XMatrix1(:,2),YMatrix1(:,2),':k','Linewidth',linewidth)

% Create ylabel
ylabel('Client Latency [ms]',...
    'Color',[0.313725501298904 0.313725501298904 0.313725501298904]);

% Create xlabel
xlabel('Threshold parameter',...
    'Color',[0.313725501298904 0.313725501298904 0.313725501298904]);

% Set the remaining axes properties
set(axes1,'FontSize',12,'XColor',...
    [0.313725501298904 0.313725501298904 0.313725501298904],'YColor',...
    [0.313725501298904 0.313725501298904 0.313725501298904],'ZColor',...
    [0.313725501298904 0.313725501298904 0.313725501298904]);
% Create legend
%legend1 = legend(axes1,'show');
%legend1 = legend([p1 p2],'Public attribute','Private attribute');
%set(legend1,'Location','northwest');
grid on;

